### PR TITLE
Improved logging and tolerance of a down host.

### PR DESCRIPTION
**Pull request by FelixGV**

### CODE REVIEW

**Comment by FelixGV** [comment]
Also added 99ce9cf to allow iterating faster (re-cloning during deployment can take a long time).

**Comment by FelixGV** [comment]
Hmm... I'm not sure that limited space in /tmp is a big concern for the following reasons:
1. Fetching a project via source control repositories is typically an operation with a small disk footprint.
2. Even though the final disk foot-print is small, the use of git and remote services like GitHub make the operation a bit long for moderately-sized repositories (such as Voldemort).
3. Because of 1 and 2, I think it would be nice if the default behavior of deploy was to keep files so that the less expensive --refresh is possible.
4. If there is truly a concern for disk usage, perhaps we could provide a clean command instead which just deletes the app folder without any other operations?

And yeah, I've been using nagini with the new --refresh flag in my own workflow.

I was not sure if the *OneHost operations should be allowed to go through when they fail. I think perhaps one thing that makes this a bit muddy is that there are some parts of the code which iterate over the *OneHost operations instead of using the corresponding *AllHost operations. We might want to clean this up? I'm not sure.

What do you think?

**Comment by cshaxu** [comment]
Thanks for the explanation and it seems clear to me now.
Yeah we may need to clean that up the *OneHost operations in NaginiClient in the future.

The commit looks good to me now.

**Comment by FelixGV** [comment]
Cool, thanks for reviewing (: !

**Pull request merged**
